#!/bin/bash

# ISP Image Checker Script
# This script checks output files generated by previous steps

echo "=== ISP Image Checker ==="

# Set working directories
PROJECT_ROOT="/home/sheldon/hls_project/vibe_crop"
DATA_DIR="$PROJECT_ROOT/data"

# Check if data directory exists
if [ ! -d "$DATA_DIR" ]; then
    echo "[Error]: Data directory $DATA_DIR does not exist"
    exit 1
fi

# Define the list of output files to check
OUTPUT_FILES=("src_image_random_generate.txt" "py_dpc_output_data.txt")

# Switch to data directory for checking
cd "$DATA_DIR"

echo "Start checking output files..."

# Initialize check counter and failure flag
FILE_CHECK_INDEX=1
MISSING_FILES=""
CHECK_OUTPUT_FAILED=0

for file in "${OUTPUT_FILES[@]}"; do
    if [ ! -f "$file" ]; then
        echo "[Error$FILE_CHECK_INDEX]: Output file $file does not exist"
        MISSING_FILES="$MISSING_FILES $file"
        CHECK_OUTPUT_FAILED=1
    else
        echo "[Success$FILE_CHECK_INDEX]: Output file $file exists"
        # Display file size and first/last few lines as verification
        FILE_SIZE=$(wc -c < "$file")
        FILE_LINES=$(wc -l < "$file")
        echo "  File size: ${FILE_SIZE} bytes"
        echo "  Total lines: ${FILE_LINES} lines"
        echo "  File content preview:"
        if [ "$FILE_LINES" -gt 10 ]; then
            echo "  --- First 5 lines ---"
            head -n 5 "$file"
            echo "  --- Last 5 lines ---"
            tail -n 5 "$file"
        else
            cat "$file"
        fi
        echo ""
    fi
    ((FILE_CHECK_INDEX++))
done

# Final check result determination
echo "Output file check completed"
if [ $CHECK_OUTPUT_FAILED -eq 1 ]; then
    echo "[FinalError]: Missing output files: $MISSING_FILES"
    exit 1
else
    echo "[FinalSuccess]: All output files check passed"
fi

echo "Image checker completed successfully"